owner: 718087881087910018

assets:
  banner: "!Asset Banner.png"
  logo: "!Asset Nexus.png"

cogs:
  - cogs.Help
  - cogs.Developer
  - cogs.Errors
  - cogs.Moderation
  - cogs.Utility
  - cogs.Modlogs
  - cogs.Settings
  - cogs.Music
  - cogs.Minecraft
  # - cogs.Listeners
  # - Jishaku

colours:
  bad: "!Colour 15158332"
  good: "!Colour 3066993"
  neutral: "!Colour 16711774"

channels:
  errors: 871371177208188948
  guilds: 906833585837867049
  votes: 907180521891692585

emojis:
  online: <:online:876417266110046239>
  idle: <:idle:876417249613856778>
  dnd: <:dnd:876417282736259082>
  tick: ":white_check_mark:"
  cross: ":x:"
  slash: <:slash:908268082903003157>